# Generated by Django 2.0.2 on 2018-02-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theroom',
            name='in_use',
        ),
        migrations.AddField(
            model_name='theroom',
            name='used_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='theroom.Session'),
        ),
    ]
