# Generated by Django 2.0.2 on 2018-02-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theroom', '0002_auto_20180223_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
